"""add basic draft_queue

Revision ID: 8577c40e2b33
Revises: 9d14b5f806d1
Create Date: 2023-02-02 22:16:13.835033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8577c40e2b33'
down_revision = '9d14b5f806d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_queue',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('queue_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_queue')
    # ### end Alembic commands ###
