"""add table for drafts

Revision ID: 9d14b5f806d1
Revises: 5f48bbb13b41
Create Date: 2023-01-23 00:08:00.025171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d14b5f806d1'
down_revision = '5f48bbb13b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('pick_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    # ### end Alembic commands ###
